package disasm

// THR field name tables for ARM64 + compressed pointers (PRODUCT AOT builds).
// Extracted from dartsdk/v*/runtime/vm/compiler/runtime_offsets_extracted.h
// (AOT + PRODUCT + TARGET_ARCH_ARM64 + DART_COMPRESSED_POINTERS sections).
//
// Each map: byte offset → short field name.

// THRFields returns the Thread offset→name map for a given Dart version string.
// Returns nil if no table is available (annotations fall back to THR+0xNN).
func THRFields(dartVersion string) map[int]string {
	switch dartVersion {
	case "2.17.6":
		return thrV217
	case "3.0.5", "3.1.0", "3.2.5", "3.3.0":
		return thrV325
	case "3.4.3", "3.5.0":
		return thrV343
	case "3.6.2", "3.7.0":
		return thrV362
	case "3.8.1":
		return thrV381
	case "3.9.2":
		return thrV392
	case "3.10.7":
		return thrV3107
	}
	return nil
}

// v2.17.6: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v2.17.6/runtime/vm/compiler/runtime_offsets_extracted.h:16818-17478
var thrV217 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "isolate",
	0x58:  "dispatch_table_array",
	0x60:  "top",
	0x68:  "end",
	0x70:  "saved_stack_limit",
	0x78:  "stack_overflow_flags",
	0x80:  "field_table_values",
	0x90:  "top_exit_frame_info",
	0x98:  "store_buffer_block",
	0xa0:  "marking_stack_block",
	0xb0:  "vm_tag",
	0xb8:  "unboxed_int64_runtime_arg",
	0xc0:  "unboxed_double_runtime_arg",
	0xc8:  "object_null",
	0xd0:  "bool_true",
	0xd8:  "bool_false",
	0xe0:  "fix_callers_target_code",
	0xe8:  "fix_allocation_stub_code",
	0xf0:  "invoke_dart_code_stub",
	0xf8:  "call_to_runtime_stub",
	0x100: "late_init_error_nofpu_stub",
	0x108: "late_init_error_fpu_stub",
	0x110: "null_error_nofpu_stub",
	0x118: "null_error_fpu_stub",
	0x120: "null_arg_error_nofpu_stub",
	0x128: "null_arg_error_fpu_stub",
	0x130: "null_cast_error_nofpu_stub",
	0x138: "null_cast_error_fpu_stub",
	0x140: "range_error_nofpu_stub",
	0x148: "range_error_fpu_stub",
	0x150: "allocate_mint_fpu_stub",
	0x158: "allocate_mint_nofpu_stub",
	0x160: "allocate_object_stub",
	0x168: "allocate_object_parameterized_stub",
	0x170: "allocate_object_slow_stub",
	0x178: "stack_overflow_nofpu_stub",
	0x180: "stack_overflow_fpu_stub",
	0x188: "switchable_call_miss_stub",
	0x1a8: "optimize_stub",
	0x1b0: "deoptimize_stub",
	0x1b8: "lazy_deopt_from_return_stub",
	0x1c0: "lazy_deopt_from_throw_stub",
	0x1c8: "slow_type_test_stub",
	0x1d0: "lazy_specialize_type_test_stub",
	0x1d8: "enter_safepoint_stub",
	0x1e0: "exit_safepoint_stub",
	0x1e8: "exit_safepoint_ignore_unwind_stub",
	0x1f0: "call_native_through_safepoint_stub",
	0x1f8: "write_barrier_ep",
	0x200: "array_write_barrier_ep",
	0x208: "call_to_runtime_ep",
	0x210: "allocate_mint_fpu_ep",
	0x218: "allocate_mint_nofpu_ep",
	0x220: "allocate_object_ep",
	0x228: "allocate_object_parameterized_ep",
	0x230: "allocate_object_slow_ep",
	0x238: "stack_overflow_nofpu_ep",
	0x240: "stack_overflow_fpu_ep",
	0x248: "megamorphic_call_checked_entry",
	0x250: "switchable_call_miss_entry",
	0x258: "optimize_ep",
	0x260: "deoptimize_ep",
	0x268: "call_native_through_safepoint_ep",
	0x270: "jump_to_frame_ep",
	0x278: "slow_type_test_ep",
	0x280: "bootstrap_native_wrapper_ep",
	0x288: "no_scope_native_wrapper_ep",
	0x290: "auto_scope_native_wrapper_ep",
	0x298: "predefined_symbols_address",
	0x2a8: "double_negate_address",
	0x2b0: "double_abs_address",
	0x2b8: "float_not_address",
	0x2c0: "float_negate_address",
	0x2c8: "float_absolute_address",
	0x2d0: "float_zerow_address",
	0x2d8: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x588: "wb_wrapper_R0",
	0x590: "wb_wrapper_R1",
	0x598: "wb_wrapper_R2",
	0x5a0: "wb_wrapper_R3",
	0x5a8: "wb_wrapper_R4",
	0x5b0: "wb_wrapper_R5",
	0x5b8: "wb_wrapper_R6",
	0x5c0: "wb_wrapper_R7",
	0x5c8: "wb_wrapper_R8",
	0x5d0: "wb_wrapper_R9",
	0x5d8: "wb_wrapper_R10",
	0x5e0: "wb_wrapper_R11",
	0x5e8: "wb_wrapper_R12",
	0x5f0: "wb_wrapper_R13",
	0x5f8: "wb_wrapper_R14",
	0x600: "wb_wrapper_R19",
	0x608: "wb_wrapper_R20",
	0x610: "wb_wrapper_R23",
	0x618: "wb_wrapper_R24",
	0x620: "active_exception",
	0x628: "active_stacktrace",
	0x630: "global_object_pool",
	0x638: "resume_pc",
	0x640: "saved_shadow_call_stack",
	0x648: "execution_state",
	0x650: "safepoint_state",
	0x658: "callback_code",
	0x660: "callback_stack_return",
	0x668: "exit_through_ffi",
	0x670: "api_top_scope",
	0x678: "double_truncate_round_supported",
	0x680: "random",
	0x688: "tsan_utils",
	0x698: "dart_stream",
	0x6a0: "isolate_group",
}

// v3.2.5: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.2.5/runtime/vm/compiler/runtime_offsets_extracted.h:20107-20870
// Also covers v3.1.0 (closest available SDK) and v3.3.0.
var thrV325 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "top",
	0x58:  "end",
	0x60:  "dispatch_table_array",
	0x68:  "field_table_values",
	0x70:  "object_null",
	0x78:  "bool_true",
	0x80:  "bool_false",
	0x88:  "empty_array",
	0x90:  "dynamic_type",
	0x98:  "fix_callers_target_code",
	0xa0:  "fix_allocation_stub_code",
	0xa8:  "invoke_dart_code_stub",
	0xb0:  "call_to_runtime_stub",
	0xb8:  "late_init_error_nofpu_stub",
	0xc0:  "late_init_error_fpu_stub",
	0xc8:  "null_error_nofpu_stub",
	0xd0:  "null_error_fpu_stub",
	0xd8:  "null_arg_error_nofpu_stub",
	0xe0:  "null_arg_error_fpu_stub",
	0xe8:  "null_cast_error_nofpu_stub",
	0xf0:  "null_cast_error_fpu_stub",
	0xf8:  "range_error_nofpu_stub",
	0x100: "range_error_fpu_stub",
	0x108: "write_error_nofpu_stub",
	0x110: "write_error_fpu_stub",
	0x118: "allocate_mint_fpu_stub",
	0x120: "allocate_mint_nofpu_stub",
	0x128: "allocate_object_stub",
	0x130: "allocate_object_parameterized_stub",
	0x138: "allocate_object_slow_stub",
	0x140: "async_exception_handler_stub",
	0x148: "resume_stub",
	0x150: "return_async_stub",
	0x158: "return_async_not_future_stub",
	0x160: "return_async_star_stub",
	0x168: "stack_overflow_nofpu_stub",
	0x170: "stack_overflow_fpu_stub",
	0x178: "switchable_call_miss_stub",
	0x198: "optimize_stub",
	0x1a0: "deoptimize_stub",
	0x1a8: "lazy_deopt_from_return_stub",
	0x1b0: "lazy_deopt_from_throw_stub",
	0x1b8: "slow_type_test_stub",
	0x1c0: "lazy_specialize_type_test_stub",
	0x1c8: "enter_safepoint_stub",
	0x1d0: "exit_safepoint_stub",
	0x1d8: "exit_safepoint_ignore_unwind_stub",
	0x1e0: "call_native_through_safepoint_stub",
	0x1e8: "write_barrier_ep",
	0x1f0: "array_write_barrier_ep",
	0x1f8: "call_to_runtime_ep",
	0x200: "allocate_mint_fpu_ep",
	0x208: "allocate_mint_nofpu_ep",
	0x210: "allocate_object_ep",
	0x218: "allocate_object_parameterized_ep",
	0x220: "allocate_object_slow_ep",
	0x228: "stack_overflow_nofpu_ep",
	0x230: "stack_overflow_fpu_ep",
	0x238: "megamorphic_call_checked_entry",
	0x240: "switchable_call_miss_entry",
	0x248: "optimize_ep",
	0x250: "deoptimize_ep",
	0x258: "call_native_through_safepoint_ep",
	0x260: "jump_to_frame_ep",
	0x268: "slow_type_test_ep",
	0x270: "bootstrap_native_wrapper_ep",
	0x278: "no_scope_native_wrapper_ep",
	0x280: "auto_scope_native_wrapper_ep",
	0x288: "predefined_symbols_address",
	0x298: "double_negate_address",
	0x2a0: "double_abs_address",
	0x2a8: "float_not_address",
	0x2b0: "float_negate_address",
	0x2b8: "float_absolute_address",
	0x2c0: "float_zerow_address",
	0x2c8: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x5e8: "wb_wrapper_R0",
	0x5f0: "wb_wrapper_R1",
	0x5f8: "wb_wrapper_R2",
	0x600: "wb_wrapper_R3",
	0x608: "wb_wrapper_R4",
	0x610: "wb_wrapper_R5",
	0x618: "wb_wrapper_R6",
	0x620: "wb_wrapper_R7",
	0x628: "wb_wrapper_R8",
	0x630: "wb_wrapper_R9",
	0x638: "wb_wrapper_R10",
	0x640: "wb_wrapper_R11",
	0x648: "wb_wrapper_R12",
	0x650: "wb_wrapper_R13",
	0x658: "wb_wrapper_R14",
	0x660: "wb_wrapper_R19",
	0x668: "wb_wrapper_R20",
	0x670: "wb_wrapper_R23",
	0x678: "wb_wrapper_R24",
	0x680: "wb_wrapper_R25",
	// High offsets (>0x680):
	0x688: "suspend_state_init_async_ep",
	0x690: "suspend_state_await_ep",
	0x698: "suspend_state_await_type_check_ep",
	0x6a0: "suspend_state_return_async_ep",
	0x6a8: "suspend_state_return_async_not_future_ep",
	0x6b0: "suspend_state_init_async_star_ep",
	0x6b8: "suspend_state_yield_async_star_ep",
	0x6c0: "suspend_state_return_async_star_ep",
	0x6c8: "suspend_state_init_sync_star_ep",
	0x6d0: "suspend_state_suspend_sync_star_ep",
	0x6d8: "suspend_state_handle_exception_ep",
	0x6e0: "isolate",
	0x6e8: "isolate_group",
	0x6f0: "saved_stack_limit",
	0x6f8: "stack_overflow_flags",
	0x700: "top_exit_frame_info",
	0x708: "store_buffer_block",
	0x710: "marking_stack_block",
	0x718: "deferred_marking_stack_block",
	0x720: "vm_tag",
	0x728: "unboxed_runtime_arg",
	0x738: "active_exception",
	0x740: "active_stacktrace",
	0x748: "global_object_pool",
	0x750: "resume_pc",
	0x758: "saved_shadow_call_stack",
	0x760: "execution_state",
	0x768: "safepoint_state",
	0x770: "exit_through_ffi",
	0x778: "api_top_scope",
	0x780: "double_truncate_round_supported",
	0x788: "next_task_id",
	0x790: "random",
	0x798: "tsan_utils",
	0x7b0: "dart_stream",
	0x7b8: "service_extension_stream",
}

// v3.4.3: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.4.3/runtime/vm/compiler/runtime_offsets_extracted.h:9204-9904
// Also covers v3.5.0.
// Delta from v3.2.5: +8 shift from fix_callers_target_code onward (RangeErrorUnboxedInt64 added).
var thrV343 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "top",
	0x58:  "end",
	0x60:  "dispatch_table_array",
	0x68:  "field_table_values",
	0x70:  "object_null",
	0x78:  "bool_true",
	0x80:  "bool_false",
	0x88:  "empty_array",
	0x90:  "empty_type_arguments",
	0x98:  "dynamic_type",
	0xa0:  "fix_callers_target_code",
	0xa8:  "fix_allocation_stub_code",
	0xb0:  "invoke_dart_code_stub",
	0xb8:  "call_to_runtime_stub",
	0xc0:  "late_init_error_nofpu_stub",
	0xc8:  "late_init_error_fpu_stub",
	0xd0:  "null_error_nofpu_stub",
	0xd8:  "null_error_fpu_stub",
	0xe0:  "null_arg_error_nofpu_stub",
	0xe8:  "null_arg_error_fpu_stub",
	0xf0:  "null_cast_error_nofpu_stub",
	0xf8:  "null_cast_error_fpu_stub",
	0x100: "range_error_nofpu_stub",
	0x108: "range_error_fpu_stub",
	0x110: "write_error_nofpu_stub",
	0x118: "write_error_fpu_stub",
	0x120: "allocate_mint_fpu_stub",
	0x128: "allocate_mint_nofpu_stub",
	0x130: "allocate_object_stub",
	0x138: "allocate_object_parameterized_stub",
	0x140: "allocate_object_slow_stub",
	0x148: "async_exception_handler_stub",
	0x150: "resume_stub",
	0x158: "return_async_stub",
	0x160: "return_async_not_future_stub",
	0x168: "return_async_star_stub",
	0x170: "stack_overflow_nofpu_stub",
	0x178: "stack_overflow_fpu_stub",
	0x180: "switchable_call_miss_stub",
	0x1a0: "optimize_stub",
	0x1a8: "deoptimize_stub",
	0x1b0: "lazy_deopt_from_return_stub",
	0x1b8: "lazy_deopt_from_throw_stub",
	0x1c0: "slow_type_test_stub",
	0x1c8: "lazy_specialize_type_test_stub",
	0x1d0: "enter_safepoint_stub",
	0x1d8: "exit_safepoint_stub",
	0x1e0: "exit_safepoint_ignore_unwind_stub",
	0x1e8: "call_native_through_safepoint_stub",
	0x1f0: "write_barrier_ep",
	0x1f8: "array_write_barrier_ep",
	0x200: "call_to_runtime_ep",
	0x208: "allocate_mint_fpu_ep",
	0x210: "allocate_mint_nofpu_ep",
	0x218: "allocate_object_ep",
	0x220: "allocate_object_parameterized_ep",
	0x228: "allocate_object_slow_ep",
	0x230: "stack_overflow_nofpu_ep",
	0x238: "stack_overflow_fpu_ep",
	0x240: "megamorphic_call_checked_entry",
	0x248: "switchable_call_miss_entry",
	0x250: "optimize_ep",
	0x258: "deoptimize_ep",
	0x260: "call_native_through_safepoint_ep",
	0x268: "jump_to_frame_ep",
	0x270: "slow_type_test_ep",
	0x278: "bootstrap_native_wrapper_ep",
	0x280: "no_scope_native_wrapper_ep",
	0x288: "auto_scope_native_wrapper_ep",
	0x290: "predefined_symbols_address",
	0x2a0: "double_negate_address",
	0x2a8: "double_abs_address",
	0x2b0: "float_not_address",
	0x2b8: "float_negate_address",
	0x2c0: "float_absolute_address",
	0x2c8: "float_zerow_address",
	0x2d0: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x5f8: "wb_wrapper_R0",
	0x600: "wb_wrapper_R1",
	0x608: "wb_wrapper_R2",
	0x610: "wb_wrapper_R3",
	0x618: "wb_wrapper_R4",
	0x620: "wb_wrapper_R5",
	0x628: "wb_wrapper_R6",
	0x630: "wb_wrapper_R7",
	0x638: "wb_wrapper_R8",
	0x640: "wb_wrapper_R9",
	0x648: "wb_wrapper_R10",
	0x650: "wb_wrapper_R11",
	0x658: "wb_wrapper_R12",
	0x660: "wb_wrapper_R13",
	0x668: "wb_wrapper_R14",
	0x670: "wb_wrapper_R19",
	0x678: "wb_wrapper_R20",
	0x680: "wb_wrapper_R23",
	0x688: "wb_wrapper_R24",
	0x690: "wb_wrapper_R25",
	// High offsets (>0x690):
	0x698: "suspend_state_init_async_ep",
	0x6a0: "suspend_state_await_ep",
	0x6a8: "suspend_state_await_type_check_ep",
	0x6b0: "suspend_state_return_async_ep",
	0x6b8: "suspend_state_return_async_not_future_ep",
	0x6c0: "suspend_state_init_async_star_ep",
	0x6c8: "suspend_state_yield_async_star_ep",
	0x6d0: "suspend_state_return_async_star_ep",
	0x6d8: "suspend_state_init_sync_star_ep",
	0x6e0: "suspend_state_suspend_sync_star_ep",
	0x6e8: "suspend_state_handle_exception_ep",
	0x6f0: "isolate",
	0x6f8: "isolate_group",
	0x700: "saved_stack_limit",
	0x708: "stack_overflow_flags",
	0x710: "top_exit_frame_info",
	0x718: "store_buffer_block",
	0x720: "marking_stack_block",
	0x730: "vm_tag",
	0x738: "unboxed_runtime_arg",
	0x748: "active_exception",
	0x750: "active_stacktrace",
	0x758: "global_object_pool",
	0x760: "resume_pc",
	0x768: "saved_shadow_call_stack",
	0x770: "execution_state",
	0x778: "safepoint_state",
	0x780: "exit_through_ffi",
	0x788: "api_top_scope",
	0x790: "double_truncate_round_supported",
	0x798: "next_task_id",
	0x7a0: "random",
	0x7a8: "tsan_utils",
	0x7c0: "dart_stream",
	0x7c8: "service_extension_stream",
}

// v3.6.2: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.6.2/runtime/vm/compiler/runtime_offsets_extracted.h:20318-21100
// Also covers v3.7.0.
// Delta from v3.4.3: shared_field_table_values added, invoke_dart_code_from_bytecode_stub added,
// resume_interpreter_ep + interpret_call_ep added, marking_stack split into old/new.
var thrV362 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "top",
	0x58:  "end",
	0x60:  "dispatch_table_array",
	0x68:  "field_table_values",
	0x70:  "shared_field_table_values",
	0x78:  "object_null",
	0x80:  "bool_true",
	0x88:  "bool_false",
	0x90:  "empty_array",
	0x98:  "empty_type_arguments",
	0xa0:  "dynamic_type",
	0xa8:  "fix_callers_target_code",
	0xb0:  "fix_allocation_stub_code",
	0xb8:  "invoke_dart_code_stub",
	0xc0:  "invoke_dart_code_from_bytecode_stub",
	0xc8:  "call_to_runtime_stub",
	0xd0:  "late_init_error_nofpu_stub",
	0xd8:  "late_init_error_fpu_stub",
	0xe0:  "null_error_nofpu_stub",
	0xe8:  "null_error_fpu_stub",
	0xf0:  "null_arg_error_nofpu_stub",
	0xf8:  "null_arg_error_fpu_stub",
	0x100: "null_cast_error_nofpu_stub",
	0x108: "null_cast_error_fpu_stub",
	0x110: "range_error_nofpu_stub",
	0x118: "range_error_fpu_stub",
	0x120: "write_error_nofpu_stub",
	0x128: "write_error_fpu_stub",
	0x130: "allocate_mint_fpu_stub",
	0x138: "allocate_mint_nofpu_stub",
	0x140: "allocate_object_stub",
	0x148: "allocate_object_parameterized_stub",
	0x150: "allocate_object_slow_stub",
	0x158: "async_exception_handler_stub",
	0x160: "resume_stub",
	0x168: "return_async_stub",
	0x170: "return_async_not_future_stub",
	0x178: "return_async_star_stub",
	0x180: "stack_overflow_nofpu_stub",
	0x188: "stack_overflow_fpu_stub",
	0x190: "switchable_call_miss_stub",
	0x1a8: "optimize_stub",
	0x1b0: "deoptimize_stub",
	0x1b8: "lazy_deopt_from_return_stub",
	0x1c0: "lazy_deopt_from_throw_stub",
	0x1c8: "slow_type_test_stub",
	0x1d0: "lazy_specialize_type_test_stub",
	0x1d8: "enter_safepoint_stub",
	0x1e0: "exit_safepoint_stub",
	0x1e8: "exit_safepoint_ignore_unwind_stub",
	0x1f0: "call_native_through_safepoint_stub",
	0x1f8: "write_barrier_ep",
	0x200: "array_write_barrier_ep",
	0x208: "call_to_runtime_ep",
	0x210: "allocate_mint_fpu_ep",
	0x218: "allocate_mint_nofpu_ep",
	0x220: "allocate_object_ep",
	0x228: "allocate_object_parameterized_ep",
	0x230: "allocate_object_slow_ep",
	0x238: "stack_overflow_nofpu_ep",
	0x240: "stack_overflow_fpu_ep",
	0x248: "megamorphic_call_checked_entry",
	0x250: "switchable_call_miss_entry",
	0x258: "optimize_ep",
	0x260: "deoptimize_ep",
	0x268: "call_native_through_safepoint_ep",
	0x270: "jump_to_frame_ep",
	0x278: "slow_type_test_ep",
	0x280: "resume_interpreter_ep",
	0x288: "bootstrap_native_wrapper_ep",
	0x290: "no_scope_native_wrapper_ep",
	0x298: "auto_scope_native_wrapper_ep",
	0x2a0: "interpret_call_ep",
	0x2a8: "predefined_symbols_address",
	0x2b8: "double_negate_address",
	0x2c0: "double_abs_address",
	0x2c8: "float_not_address",
	0x2d0: "float_negate_address",
	0x2d8: "float_absolute_address",
	0x2e0: "float_zerow_address",
	0x2e8: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x660: "wb_wrapper_R0",
	0x668: "wb_wrapper_R1",
	0x670: "wb_wrapper_R2",
	0x678: "wb_wrapper_R3",
	0x680: "wb_wrapper_R4",
	0x688: "wb_wrapper_R5",
	0x690: "wb_wrapper_R6",
	0x698: "wb_wrapper_R7",
	0x6a0: "wb_wrapper_R8",
	0x6a8: "wb_wrapper_R9",
	0x6b0: "wb_wrapper_R10",
	0x6b8: "wb_wrapper_R11",
	0x6c0: "wb_wrapper_R12",
	0x6c8: "wb_wrapper_R13",
	0x6d0: "wb_wrapper_R14",
	0x6d8: "wb_wrapper_R19",
	0x6e0: "wb_wrapper_R20",
	0x6e8: "wb_wrapper_R23",
	0x6f0: "wb_wrapper_R24",
	0x6f8: "wb_wrapper_R25",
	// High offsets (>0x6f8):
	0x700: "suspend_state_init_async_ep",
	0x708: "suspend_state_await_ep",
	0x710: "suspend_state_await_type_check_ep",
	0x718: "suspend_state_return_async_ep",
	0x720: "suspend_state_return_async_not_future_ep",
	0x728: "suspend_state_init_async_star_ep",
	0x730: "suspend_state_yield_async_star_ep",
	0x738: "suspend_state_return_async_star_ep",
	0x740: "suspend_state_init_sync_star_ep",
	0x748: "suspend_state_suspend_sync_star_ep",
	0x750: "suspend_state_handle_exception_ep",
	0x758: "isolate",
	0x760: "isolate_group",
	0x768: "saved_stack_limit",
	0x770: "stack_overflow_flags",
	0x778: "top_exit_frame_info",
	0x780: "store_buffer_block",
	0x788: "old_marking_stack_block",
	0x790: "new_marking_stack_block",
	0x7a0: "vm_tag",
	0x7a8: "unboxed_runtime_arg",
	0x7b8: "active_exception",
	0x7c0: "active_stacktrace",
	0x7c8: "global_object_pool",
	0x7d0: "resume_pc",
	0x7d8: "saved_shadow_call_stack",
	0x7e0: "execution_state",
	0x7e8: "safepoint_state",
	0x7f0: "exit_through_ffi",
	0x7f8: "api_top_scope",
	0x800: "double_truncate_round_supported",
	0x808: "next_task_id",
	0x810: "random",
	0x818: "tsan_utils",
	0x830: "dart_stream",
	0x838: "service_extension_stream",
}

// v3.8.1: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.8.1/runtime/vm/compiler/runtime_offsets_extracted.h:9347-9900
// Delta from v3.6.2: exit_safepoint_ignore_unwind_stub removed (shifts all ep offsets by -8),
// RememberCard and ExitSafepointIgnoreUnwindInProgress removed from LEAF list.
var thrV381 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "top",
	0x58:  "end",
	0x60:  "dispatch_table_array",
	0x68:  "field_table_values",
	0x70:  "shared_field_table_values",
	0x78:  "object_null",
	0x80:  "bool_true",
	0x88:  "bool_false",
	0x90:  "empty_array",
	0x98:  "empty_type_arguments",
	0xa0:  "dynamic_type",
	0xa8:  "fix_callers_target_code",
	0xb0:  "fix_allocation_stub_code",
	0xb8:  "invoke_dart_code_stub",
	0xc0:  "invoke_dart_code_from_bytecode_stub",
	0xc8:  "call_to_runtime_stub",
	0xd0:  "late_init_error_nofpu_stub",
	0xd8:  "late_init_error_fpu_stub",
	0xe0:  "null_error_nofpu_stub",
	0xe8:  "null_error_fpu_stub",
	0xf0:  "null_arg_error_nofpu_stub",
	0xf8:  "null_arg_error_fpu_stub",
	0x100: "null_cast_error_nofpu_stub",
	0x108: "null_cast_error_fpu_stub",
	0x110: "range_error_nofpu_stub",
	0x118: "range_error_fpu_stub",
	0x120: "write_error_nofpu_stub",
	0x128: "write_error_fpu_stub",
	0x130: "allocate_mint_fpu_stub",
	0x138: "allocate_mint_nofpu_stub",
	0x140: "allocate_object_stub",
	0x148: "allocate_object_parameterized_stub",
	0x150: "allocate_object_slow_stub",
	0x158: "async_exception_handler_stub",
	0x160: "resume_stub",
	0x168: "return_async_stub",
	0x170: "return_async_not_future_stub",
	0x178: "return_async_star_stub",
	0x180: "stack_overflow_nofpu_stub",
	0x188: "stack_overflow_fpu_stub",
	0x190: "switchable_call_miss_stub",
	0x1a8: "optimize_stub",
	0x1b0: "deoptimize_stub",
	0x1b8: "lazy_deopt_from_return_stub",
	0x1c0: "lazy_deopt_from_throw_stub",
	0x1c8: "slow_type_test_stub",
	0x1d0: "lazy_specialize_type_test_stub",
	0x1d8: "enter_safepoint_stub",
	0x1e0: "exit_safepoint_stub",
	0x1e8: "call_native_through_safepoint_stub",
	0x1f0: "write_barrier_ep",
	0x1f8: "array_write_barrier_ep",
	0x200: "call_to_runtime_ep",
	0x208: "allocate_mint_fpu_ep",
	0x210: "allocate_mint_nofpu_ep",
	0x218: "allocate_object_ep",
	0x220: "allocate_object_parameterized_ep",
	0x228: "allocate_object_slow_ep",
	0x230: "stack_overflow_nofpu_ep",
	0x238: "stack_overflow_fpu_ep",
	0x240: "megamorphic_call_checked_entry",
	0x248: "switchable_call_miss_entry",
	0x250: "optimize_ep",
	0x258: "deoptimize_ep",
	0x260: "call_native_through_safepoint_ep",
	0x268: "jump_to_frame_ep",
	0x270: "slow_type_test_ep",
	0x278: "resume_interpreter_ep",
	0x280: "bootstrap_native_wrapper_ep",
	0x288: "no_scope_native_wrapper_ep",
	0x290: "auto_scope_native_wrapper_ep",
	0x298: "interpret_call_ep",
	0x2a0: "predefined_symbols_address",
	0x2b0: "double_negate_address",
	0x2b8: "double_abs_address",
	0x2c0: "float_not_address",
	0x2c8: "float_negate_address",
	0x2d0: "float_absolute_address",
	0x2d8: "float_zerow_address",
	0x2e0: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x648: "wb_wrapper_R0",
	0x650: "wb_wrapper_R1",
	0x658: "wb_wrapper_R2",
	0x660: "wb_wrapper_R3",
	0x668: "wb_wrapper_R4",
	0x670: "wb_wrapper_R5",
	0x678: "wb_wrapper_R6",
	0x680: "wb_wrapper_R7",
	0x688: "wb_wrapper_R8",
	0x690: "wb_wrapper_R9",
	0x698: "wb_wrapper_R10",
	0x6a0: "wb_wrapper_R11",
	0x6a8: "wb_wrapper_R12",
	0x6b0: "wb_wrapper_R13",
	0x6b8: "wb_wrapper_R14",
	0x6c0: "wb_wrapper_R19",
	0x6c8: "wb_wrapper_R20",
	0x6d0: "wb_wrapper_R23",
	0x6d8: "wb_wrapper_R24",
	0x6e0: "wb_wrapper_R25",
	// High offsets (>0x6e0):
	0x6e8: "suspend_state_init_async_ep",
	0x6f0: "suspend_state_await_ep",
	0x6f8: "suspend_state_await_type_check_ep",
	0x700: "suspend_state_return_async_ep",
	0x708: "suspend_state_return_async_not_future_ep",
	0x710: "suspend_state_init_async_star_ep",
	0x718: "suspend_state_yield_async_star_ep",
	0x720: "suspend_state_return_async_star_ep",
	0x728: "suspend_state_init_sync_star_ep",
	0x730: "suspend_state_suspend_sync_star_ep",
	0x738: "suspend_state_handle_exception_ep",
	0x740: "isolate",
	0x748: "isolate_group",
	0x750: "saved_stack_limit",
	0x758: "stack_overflow_flags",
	0x760: "top_exit_frame_info",
	0x768: "store_buffer_block",
	0x770: "old_marking_stack_block",
	0x778: "new_marking_stack_block",
	0x788: "vm_tag",
	0x790: "unboxed_runtime_arg",
	0x7a0: "active_exception",
	0x7a8: "active_stacktrace",
	0x7b0: "global_object_pool",
	0x7b8: "resume_pc",
	0x7c0: "saved_shadow_call_stack",
	0x7c8: "execution_state",
	0x7d0: "safepoint_state",
	0x7d8: "exit_through_ffi",
	0x7e0: "api_top_scope",
	0x7e8: "double_truncate_round_supported",
	0x7f0: "next_task_id",
	0x7f8: "random",
	0x800: "tsan_utils",
	0x818: "dart_stream",
	0x820: "service_extension_stream",
}

// v3.9.2: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.9.2/runtime/vm/compiler/runtime_offsets_extracted.h:20369-21163
// Delta from v3.8.1: -TraceICCall, +StaticFieldAccessedWithoutIsolateError,
// +ThrowIfValueCantBeShared, +ConvertToInstanceTypeArguments, +ResolveExternalCall,
// +InitializeSharedField. AllocateArray_ep shifts to 0x2f0, wb_wrappers to 0x678.
var thrV392 = map[int]string{
	0x20:  "top_resource",
	0x38:  "stack_limit",
	0x40:  "write_barrier_mask",
	0x48:  "heap_base",
	0x50:  "top",
	0x58:  "end",
	0x60:  "dispatch_table_array",
	0x68:  "field_table_values",
	0x70:  "shared_field_table_values",
	0x78:  "object_null",
	0x80:  "bool_true",
	0x88:  "bool_false",
	0x90:  "empty_array",
	0x98:  "empty_type_arguments",
	0xa0:  "dynamic_type",
	0xa8:  "fix_callers_target_code",
	0xb0:  "fix_allocation_stub_code",
	0xb8:  "invoke_dart_code_stub",
	0xc0:  "invoke_dart_code_from_bytecode_stub",
	0xc8:  "call_to_runtime_stub",
	0xd0:  "late_init_error_nofpu_stub",
	0xd8:  "late_init_error_fpu_stub",
	0xe0:  "null_error_nofpu_stub",
	0xe8:  "null_error_fpu_stub",
	0xf0:  "null_arg_error_nofpu_stub",
	0xf8:  "null_arg_error_fpu_stub",
	0x100: "null_cast_error_nofpu_stub",
	0x108: "null_cast_error_fpu_stub",
	0x110: "range_error_nofpu_stub",
	0x118: "range_error_fpu_stub",
	0x120: "write_error_nofpu_stub",
	0x128: "write_error_fpu_stub",
	0x130: "field_access_error_nofpu_stub",
	0x138: "field_access_error_fpu_stub",
	0x140: "allocate_mint_fpu_stub",
	0x148: "allocate_mint_nofpu_stub",
	0x150: "allocate_object_stub",
	0x158: "allocate_object_parameterized_stub",
	0x160: "allocate_object_slow_stub",
	0x168: "async_exception_handler_stub",
	0x170: "resume_stub",
	0x178: "return_async_stub",
	0x180: "return_async_not_future_stub",
	0x188: "return_async_star_stub",
	0x190: "stack_overflow_nofpu_stub",
	0x198: "stack_overflow_fpu_stub",
	0x1a0: "switchable_call_miss_stub",
	0x1b8: "optimize_stub",
	0x1c0: "deoptimize_stub",
	0x1c8: "lazy_deopt_from_return_stub",
	0x1d0: "lazy_deopt_from_throw_stub",
	0x1d8: "slow_type_test_stub",
	0x1e0: "lazy_specialize_type_test_stub",
	0x1e8: "enter_safepoint_stub",
	0x1f0: "exit_safepoint_stub",
	0x1f8: "call_native_through_safepoint_stub",
	0x200: "write_barrier_ep",
	0x208: "array_write_barrier_ep",
	0x210: "call_to_runtime_ep",
	0x218: "allocate_mint_fpu_ep",
	0x220: "allocate_mint_nofpu_ep",
	0x228: "allocate_object_ep",
	0x230: "allocate_object_parameterized_ep",
	0x238: "allocate_object_slow_ep",
	0x240: "stack_overflow_nofpu_ep",
	0x248: "stack_overflow_fpu_ep",
	0x250: "megamorphic_call_checked_entry",
	0x258: "switchable_call_miss_entry",
	0x260: "optimize_ep",
	0x268: "deoptimize_ep",
	0x270: "call_native_through_safepoint_ep",
	0x278: "jump_to_frame_ep",
	0x280: "slow_type_test_ep",
	0x288: "resume_interpreter_ep",
	0x290: "bootstrap_native_wrapper_ep",
	0x298: "no_scope_native_wrapper_ep",
	0x2a0: "auto_scope_native_wrapper_ep",
	0x2a8: "interpret_call_ep",
	0x2b0: "predefined_symbols_address",
	0x2c0: "double_negate_address",
	0x2c8: "double_abs_address",
	0x2d0: "float_not_address",
	0x2d8: "float_negate_address",
	0x2e0: "float_absolute_address",
	0x2e8: "float_zerow_address",
	0x2f0: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x678: "wb_wrapper_R0",
	0x680: "wb_wrapper_R1",
	0x688: "wb_wrapper_R2",
	0x690: "wb_wrapper_R3",
	0x698: "wb_wrapper_R4",
	0x6a0: "wb_wrapper_R5",
	0x6a8: "wb_wrapper_R6",
	0x6b0: "wb_wrapper_R7",
	0x6b8: "wb_wrapper_R8",
	0x6c0: "wb_wrapper_R9",
	0x6c8: "wb_wrapper_R10",
	0x6d0: "wb_wrapper_R11",
	0x6d8: "wb_wrapper_R12",
	0x6e0: "wb_wrapper_R13",
	0x6e8: "wb_wrapper_R14",
	0x6f0: "wb_wrapper_R19",
	0x6f8: "wb_wrapper_R20",
	0x700: "wb_wrapper_R23",
	0x708: "wb_wrapper_R24",
	0x710: "wb_wrapper_R25",
	// Suspend state entry points
	0x718: "suspend_state_init_async_ep",
	0x720: "suspend_state_await_ep",
	0x728: "suspend_state_await_type_check_ep",
	0x730: "suspend_state_return_async_ep",
	0x738: "suspend_state_return_async_not_future_ep",
	0x740: "suspend_state_init_async_star_ep",
	0x748: "suspend_state_yield_async_star_ep",
	0x750: "suspend_state_return_async_star_ep",
	0x758: "suspend_state_init_sync_star_ep",
	0x760: "suspend_state_suspend_sync_star_ep",
	0x768: "suspend_state_handle_exception_ep",
	// High offsets
	0x770: "isolate",
	0x778: "isolate_group",
	0x780: "saved_stack_limit",
	0x788: "stack_overflow_flags",
	0x790: "top_exit_frame_info",
	0x798: "store_buffer_block",
	0x7a0: "old_marking_stack_block",
	0x7a8: "new_marking_stack_block",
	0x7b8: "vm_tag",
	0x7c0: "unboxed_runtime_arg",
	0x7d0: "active_exception",
	0x7d8: "active_stacktrace",
	0x7e0: "global_object_pool",
	0x7e8: "resume_pc",
	0x7f0: "saved_shadow_call_stack",
	0x7f8: "execution_state",
	0x800: "safepoint_state",
	0x808: "exit_through_ffi",
	0x810: "api_top_scope",
	0x818: "double_truncate_round_supported",
	0x820: "next_task_id",
	0x828: "random",
	0x830: "tsan_utils",
	0x850: "dart_stream",
	0x858: "service_extension_stream",
}

// v3.10.7: PRODUCT AOT + ARM64 + DART_COMPRESSED_POINTERS
// Source: dartsdk/v3.10.7/runtime/vm/compiler/runtime_offsets_extracted.h:20210-21000
var thrV3107 = map[int]string{
	0x20:  "top_resource",
	0x48:  "stack_limit",
	0x50:  "write_barrier_mask",
	0x58:  "heap_base",
	0x60:  "top",
	0x68:  "end",
	0x70:  "dispatch_table_array",
	0x78:  "field_table_values",
	0x80:  "shared_field_table_values",
	0x88:  "object_null",
	0x90:  "bool_true",
	0x98:  "bool_false",
	0xa0:  "empty_array",
	0xa8:  "empty_type_arguments",
	0xb0:  "dynamic_type",
	0xb8:  "fix_callers_target_code",
	0xc0:  "fix_allocation_stub_code",
	0xc8:  "invoke_dart_code_stub",
	0xd0:  "invoke_dart_code_from_bytecode_stub",
	0xd8:  "call_to_runtime_stub",
	0xe0:  "late_init_error_nofpu_stub",
	0xe8:  "late_init_error_fpu_stub",
	0xf0:  "null_error_nofpu_stub",
	0xf8:  "null_error_fpu_stub",
	0x100: "null_arg_error_nofpu_stub",
	0x108: "null_arg_error_fpu_stub",
	0x110: "null_cast_error_nofpu_stub",
	0x118: "null_cast_error_fpu_stub",
	0x120: "range_error_nofpu_stub",
	0x128: "range_error_fpu_stub",
	0x130: "write_error_nofpu_stub",
	0x138: "write_error_fpu_stub",
	0x140: "field_access_error_nofpu_stub",
	0x148: "field_access_error_fpu_stub",
	0x150: "allocate_mint_fpu_stub",
	0x158: "allocate_mint_nofpu_stub",
	0x160: "async_exception_handler_stub",
	0x168: "resume_stub",
	0x170: "return_async_stub",
	0x178: "return_async_not_future_stub",
	0x180: "return_async_star_stub",
	0x188: "stack_overflow_nofpu_stub",
	0x190: "stack_overflow_fpu_stub",
	0x198: "switchable_call_miss_stub",
	0x1b0: "optimize_stub",
	0x1b8: "deoptimize_stub",
	0x1c0: "lazy_deopt_from_return_stub",
	0x1c8: "lazy_deopt_from_throw_stub",
	0x1d0: "slow_type_test_stub",
	0x1d8: "lazy_specialize_type_test_stub",
	0x1e0: "enter_safepoint_stub",
	0x1e8: "exit_safepoint_stub",
	0x1f0: "call_native_through_safepoint_stub",
	0x1f8: "write_barrier_ep",
	0x200: "array_write_barrier_ep",
	0x208: "call_to_runtime_ep",
	0x210: "allocate_mint_fpu_ep",
	0x218: "allocate_mint_nofpu_ep",
	0x220: "allocate_object_ep",
	0x228: "allocate_object_parameterized_ep",
	0x230: "allocate_object_slow_ep",
	0x238: "stack_overflow_nofpu_ep",
	0x240: "stack_overflow_fpu_ep",
	0x248: "megamorphic_call_checked_entry",
	0x250: "switchable_call_miss_entry",
	0x258: "optimize_ep",
	0x260: "deoptimize_ep",
	0x268: "call_native_through_safepoint_ep",
	0x270: "jump_to_frame_ep",
	0x278: "slow_type_test_ep",
	0x280: "resume_interpreter_ep",
	0x288: "bootstrap_native_wrapper_ep",
	0x290: "no_scope_native_wrapper_ep",
	0x298: "auto_scope_native_wrapper_ep",
	0x2a0: "interpret_call_ep",
	0x2a8: "predefined_symbols_address",
	0x2b8: "double_negate_address",
	0x2c0: "double_abs_address",
	0x2c8: "float_not_address",
	0x2d0: "float_negate_address",
	0x2d8: "float_absolute_address",
	0x2e0: "float_zerow_address",
	0x2e8: "AllocateArray_ep",
	// write_barrier_wrappers[R0..R25]
	0x570: "wb_wrapper_R0",
	0x578: "wb_wrapper_R1",
	0x580: "wb_wrapper_R2",
	0x588: "wb_wrapper_R3",
	0x590: "wb_wrapper_R4",
	0x598: "wb_wrapper_R5",
	0x5a0: "wb_wrapper_R6",
	0x5a8: "wb_wrapper_R7",
	0x5b0: "wb_wrapper_R8",
	0x5b8: "wb_wrapper_R9",
	0x5c0: "wb_wrapper_R10",
	0x5c8: "wb_wrapper_R11",
	0x5d0: "wb_wrapper_R12",
	0x5d8: "wb_wrapper_R13",
	0x5e0: "wb_wrapper_R14",
	0x5e8: "wb_wrapper_R19",
	0x5f0: "wb_wrapper_R20",
	0x5f8: "wb_wrapper_R23",
	0x600: "wb_wrapper_R24",
	0x608: "wb_wrapper_R25",
	// High offsets (>0x610):
	0x610: "suspend_state_init_async_ep",
	0x618: "suspend_state_await_ep",
	0x620: "suspend_state_await_type_check_ep",
	0x628: "suspend_state_return_async_ep",
	0x630: "suspend_state_return_async_not_future_ep",
	0x638: "suspend_state_init_async_star_ep",
	0x640: "suspend_state_yield_async_star_ep",
	0x648: "suspend_state_return_async_star_ep",
	0x650: "suspend_state_init_sync_star_ep",
	0x658: "suspend_state_suspend_sync_star_ep",
	0x660: "suspend_state_handle_exception_ep",
	0x668: "isolate",
	0x670: "isolate_group",
	0x678: "saved_stack_limit",
	0x680: "stack_overflow_flags",
	0x688: "top_exit_frame_info",
	0x690: "store_buffer_block",
	0x698: "old_marking_stack_block",
	0x6a0: "new_marking_stack_block",
	0x6b0: "vm_tag",
	0x6b8: "active_exception",
	0x6c0: "active_stacktrace",
	0x6c8: "global_object_pool",
	0x6d0: "resume_pc",
	0x6d8: "saved_shadow_call_stack",
	0x6e0: "execution_state",
	0x6e8: "safepoint_state",
	0x6f0: "exit_through_ffi",
	0x888: "api_top_scope",
	0x890: "double_truncate_round_supported",
	0x898: "unboxed_runtime_arg",
	0x8a8: "next_task_id",
	0x8b0: "random",
	0x8b8: "tsan_utils",
	0x8c8: "user_tag",
	0x8d0: "current_tag",
	0x8d8: "default_tag",
	0x8f0: "dart_stream",
	0x8f8: "service_extension_stream",
}

// Runtime entry point names by version, ordered as in runtime_entry_list.h.
// Each entry occupies 8 bytes (one uword) in the Thread struct.
// Offset = AllocateArray_ep + index*8.
// RUNTIME_ENTRY_LIST entries come first, then LEAF_RUNTIME_ENTRY_LIST entries.

// v2.17.6: 55 RUNTIME + 31 LEAF = 86 entries from 0x2d8 to 0x588 (exclusive).
var runtimeEntriesV217 = []string{
	// RUNTIME_ENTRY_LIST (55)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "BoxDouble",
	"BreakpointRuntimeHandler", "SingleStepHandler", "CloneContext",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "StackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "SwitchableCallMiss", "NotLoaded",
	// LEAF_RUNTIME_ENTRY_LIST (31)
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"TsanLoadAcquire", "TsanStoreRelease",
}

// v3.2.5: 64 RUNTIME + 36 LEAF = 100 entries from 0x2c8 to 0x5e8 (exclusive).
// Also used for v3.1.0 (closest available SDK).
var runtimeEntriesV325 = []string{
	// RUNTIME_ENTRY_LIST (64)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend",
	// LEAF_RUNTIME_ENTRY_LIST (36)
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanLoadAcquire", "TsanStoreRelease",
	"TryDoubleAsInteger", "MemoryMove",
}

// v3.4.3: 65 RUNTIME + 36 LEAF = 101 entries from 0x2d0 to 0x5f8 (exclusive).
// Also used for v3.5.0.
// Delta from v3.2.5: +RangeErrorUnboxedInt64, +WriteError replaces old position.
var runtimeEntriesV343 = []string{
	// RUNTIME_ENTRY_LIST (65)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend",
	// LEAF_RUNTIME_ENTRY_LIST (36)
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanLoadAcquire", "TsanStoreRelease",
	"TryDoubleAsInteger", "MemoryMove",
}

// v3.6.2: 73 RUNTIME + 38 LEAF = 111 entries from 0x2e8 to 0x660 (exclusive).
// Also used for v3.7.0.
// Delta from v3.4.3: -NonBoolTypeError, +LateFieldAlreadyInitializedError,
// +8 new entries at end. LEAF: MarkingStackBlockProcess split into Old+New, +LibcFmod.
var runtimeEntriesV362 = []string{
	// RUNTIME_ENTRY_LIST (73)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"LateFieldAlreadyInitializedError",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend",
	"AllocateSubtypeTestCache", "GetFieldForDispatch",
	"AdjustArgumentsDesciptorForImplicitClosure",
	"ClosureArgumentsValid", "ResolveCallFunction",
	"InterpretedInstanceCallMissHandler",
	"InvokeNoSuchMethod", "ResumeInterpreter",
	// LEAF_RUNTIME_ENTRY_LIST (38)
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "OldMarkingStackBlockProcess", "NewMarkingStackBlockProcess",
	"RememberCard", "EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFmod",
	"LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanLoadAcquire", "TsanStoreRelease",
	"TryDoubleAsInteger", "MemoryMove",
}

// v3.8.1: 73 RUNTIME + 36 LEAF = 109 entries from 0x2e0 to 0x648 (exclusive).
// Delta from v3.6.2: -RememberCard, -ExitSafepointIgnoreUnwindInProgress from LEAF.
// exit_safepoint_ignore_unwind_stub removed → all ep offsets shift -8.
var runtimeEntriesV381 = []string{
	// RUNTIME_ENTRY_LIST (73) — identical to v3.6.2
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"LateFieldAlreadyInitializedError",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend",
	"AllocateSubtypeTestCache", "GetFieldForDispatch",
	"AdjustArgumentsDesciptorForImplicitClosure",
	"ClosureArgumentsValid", "ResolveCallFunction",
	"InterpretedInstanceCallMissHandler",
	"InvokeNoSuchMethod", "ResumeInterpreter",
	// LEAF_RUNTIME_ENTRY_LIST (36) — RememberCard and ExitSafepointIgnoreUnwindInProgress removed
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "OldMarkingStackBlockProcess", "NewMarkingStackBlockProcess",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFmod",
	"LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanLoadAcquire", "TsanStoreRelease",
	"TryDoubleAsInteger", "MemoryMove",
}

// v3.9.2: 77 RUNTIME + 36 LEAF = 113 entries from 0x2f0 to 0x678 (exclusive).
// Delta from v3.8.1: -TraceICCall, +StaticFieldAccessedWithoutIsolateError,
// +ThrowIfValueCantBeShared, +ConvertToInstanceTypeArguments, +ResolveExternalCall,
// +InitializeSharedField. LEAF identical to v3.8.1.
var runtimeEntriesV392 = []string{
	// RUNTIME_ENTRY_LIST (77)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"StaticFieldAccessedWithoutIsolateError", "ThrowIfValueCantBeShared",
	"LateFieldAlreadyInitializedError",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend",
	"AllocateSubtypeTestCache", "GetFieldForDispatch",
	"AdjustArgumentsDesciptorForImplicitClosure",
	"ConvertToInstanceTypeArguments",
	"ClosureArgumentsValid", "ResolveCallFunction", "ResolveExternalCall",
	"InterpretedInstanceCallMissHandler",
	"InvokeNoSuchMethod", "ResumeInterpreter", "InitializeSharedField",
	// LEAF_RUNTIME_ENTRY_LIST (36) — identical to v3.8.1
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "OldMarkingStackBlockProcess", "NewMarkingStackBlockProcess",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFmod",
	"LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanLoadAcquire", "TsanStoreRelease",
	"TryDoubleAsInteger", "MemoryMove",
}

// v3.10.7: 81 RUNTIME entries from 0x2e8 to 0x570 (exclusive). No LEAF in block.
var runtimeEntriesV3107 = []string{
	// RUNTIME_ENTRY_LIST (81)
	"AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
	"AllocateFloat64x2", "AllocateInt32x4", "AllocateTypedData", "AllocateClosure",
	"AllocateContext", "AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
	"BreakpointRuntimeHandler", "SingleStepHandler", "ResumptionBreakpointHandler",
	"CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue", "NoSuchMethodError",
	"OptimizeInvokedFunction", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField",
	"StaticFieldAccessedWithoutIsolateError", "ThrowIfValueCantBeShared",
	"LateFieldAlreadyInitializedError",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"FfiAsyncCallbackSend", "AllocateSubtypeTestCache", "GetFieldForDispatch",
	"AdjustArgumentsDescriptorForImplicitClosure", "ConvertToInstanceTypeArguments",
	"ClosureArgumentsValid", "ResolveCallFunction", "ResolveExternalCall",
	"FfiCall", "CheckFunctionArgumentTypes",
	"InterpretedInstanceCallMissHandler",
	"InvokeNoSuchMethod", "ResumeInterpreter", "InitializeSharedField",
}

// v3.10.7: 50 LEAF entries stored in separate block at 0x6f8 (after exit_through_ffi at 0x6f0).
// In v3.10.7, LEAF entries moved from the main runtime entry block to their own block.
// Source: dartsdk/v3.10.7/runtime/vm/thread.h:1512-1514 (LEAF_RUNTIME_ENTRY_LIST(DECLARE_MEMBERS))
var leafEntriesV3107 = []string{
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "OldMarkingStackBlockProcess", "NewMarkingStackBlockProcess",
	"EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFmod",
	"LibcFloor", "LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan", "LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanAtomic32Load", "TsanAtomic32Store", "TsanAtomic64Load", "TsanAtomic64Store",
	"TsanRead1", "TsanRead2", "TsanRead4", "TsanRead8", "TsanRead16",
	"TsanWrite1", "TsanWrite2", "TsanWrite4", "TsanWrite8", "TsanWrite16",
	"TsanFuncEntry", "TsanFuncExit",
	"TryDoubleAsInteger", "MemoryMove",
}

func init() {
	mergeRuntimeEntries(thrV217, 0x2d8, runtimeEntriesV217)
	mergeRuntimeEntries(thrV325, 0x2c8, runtimeEntriesV325)
	mergeRuntimeEntries(thrV343, 0x2d0, runtimeEntriesV343)
	mergeRuntimeEntries(thrV362, 0x2e8, runtimeEntriesV362)
	mergeRuntimeEntries(thrV381, 0x2e0, runtimeEntriesV381)
	mergeRuntimeEntries(thrV392, 0x2f0, runtimeEntriesV392)
	mergeRuntimeEntries(thrV3107, 0x2e8, runtimeEntriesV3107)
	mergeRuntimeEntries(thrV3107, 0x6f8, leafEntriesV3107) // LEAF block after exit_through_ffi
}

// mergeRuntimeEntries adds computed runtime entry point names to a THR field map.
// base is the offset of the first entry (AllocateArray). Each subsequent entry is +8.
func mergeRuntimeEntries(m map[int]string, base int, names []string) {
	for i, name := range names {
		off := base + i*8
		if _, exists := m[off]; !exists {
			m[off] = name + "_ep"
		}
	}
}
